name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: sudo apt-get install -y cmake g++ libopenmpi-dev
    - name: Build
      run: |
        chmod +x build.sh
        ./build.sh
    - name: Compile matrix_mult.cpp
      run: mpic++ -c -I../../test/** src/matrix_mult.cpp -o matrix_mult.o

    - name: Compile test_matrix_multiplication.cpp
      run: mpic++ -c -I../../** test/test_matrix_multiplication.cpp -o test_matrix_multiplication.o

    - name: Link objects and create executable
      run: mpic++ matrix_mult.o test_matrix_multiplication.o -o test_matrix_multiplication
    - name: Run tests
      run: mpirun ./test_matrix_multiplication
