name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: sudo apt-get install cmake g++ -y
    - name: Install MPI
      run: sudo apt-get install -y libopenmpi-dev
    - name: Build
      run: |
        chmod +x build.sh
        ./build.sh
    - name: Test
      run: ./test/test_matrix_multiplication.cpp