name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libopenmpi-dev

      - name: Compile tests
        run: |
          mpic++ -I./SEMyProject_part2/** -o test_matrix_multiplication SEMyProject_part2/test/test_matrix_multiplication.cpp SEMyProject_part2/src/matrix_mult.cpp

      - name: Run tests
        run: ./test_matrix_multiplication
